[[collection]]
type = "entry"
link = "https://johnresig.com/blog/write-code-every-day"
title = "Write Code Every Day"
subtitle = "John Resig"

[[collection]]
type = "entry"
link = "https://overreacted.io/the-elements-of-ui-engineering"
title = "The Elements of UI Engineering"
subtitle = "Dan Abramov"

[[collection]]
type = "entry"
title = "Teach Yourself Programming in Ten Years"
link = "https://norvig.com/21-days.html"
subtitle = "Peter Norvig"

[[collection]]
type = 'br'

[[collection]]
type = "entry"
link = "https://www.scattered-thoughts.net/writing/reflections-on-a-decade-of-coding"
title = "Reflections on a decade of coding"
subtitle = "Jamie Brandon"

[[collection]]
type = "entry"
link = "https://www.ee.torontomu.ca/~elf/hack"
title = "Hacker's Wisdom"
subtitle = "~elf/hack"

[[collection]]
type = "entry"
link = "https://drmingdrmer.github.io/tech/bla/2018/09/27/toaster.html"
title = "软件工程是个面包机"
subtitle = "drmingdrmer.github.io"

[[collection]]
type = "entry"
link = "https://shud.in/thoughts/the-non-existing-nostalgic"
title = "不存在的乡愁"
subtitle = "shud.in"
