[[collection]]
type = "art"
img = "/assets/book-3.jpg"
title = "The Old Man and the Sea"
link = "https://example.com"
subtitle = "[American] Ernest Hemingway"
content = "A novella that tells the story of Santiago, an aging Cuban fisherman who struggles with a giant marlin far out in the Gulf Stream. The story is a tale of endurance, perseverance, and the human spirit's struggle against nature. It explores themes of courage, pride, and the relationship between man and the natural world."
footer = "⭐︎⭐︎⭐︎⭐︎⭐︎"

[[collection]]
type = "art"
img = "/assets/book-2.jpg"
title = "To Kill a Mockingbird"
link = "https://example.com"
subtitle = "[American] Harper Lee"
content = "A novel set in the American South during the 1930s. It tells the story of Scout Finch, her brother Jem, and their father Atticus, a lawyer who defends a black man falsely accused of raping a white woman. The novel addresses themes of racial injustice, moral growth, and the loss of innocence."
footer = "⭐︎⭐︎⭐︎"

[[collection]]
type = "art"
img = "/assets/book-1.jpg"
title = "1984"
link = "https://example.com"
subtitle = "[British] George Orwell"
content = "A dystopian novel set in a totalitarian society ruled by the Party, which has total control over every aspect of people's lives. The story follows Winston Smith, a low-ranking member of the Party, as he becomes disillusioned with the oppressive regime and begins to rebel against it. The novel explores themes of surveillance, censorship, and the manipulation of truth."
footer = "⭐︎⭐︎⭐︎⭐︎"
