[[project]]
name = "lorem"
desc = "Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et!"
tags = ["nisi", "saepe"]
links = [
    {name = "github", url = "https://example.com"},
    {name = "docs", url = "https://example.com"},
]

[[project]]
name = "dolor sit"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["amet", "ipsum", "vero", "optio"]
links = [
    {name = "github", url = "https://example.com"},
]

[[project]]
name = "ipsum"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit."
tags = ["lorem", "ipsum"]
links = [
    {name = "source", url = "https://example.com"},
    {name = "docs", url = "https://example.com"},
]

[[project]]
name = "amet"
desc = "Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! \n\nAtque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["lorem", "vero"]
links = [
    {name = "website", url = "https://example.com"},
    {name = "github", url = "https://example.com"},
    {name = "docs", url = "https://example.com"},
    {name = "wiki", url = "https://example.com"},
]

[[project]]
name = "praesentium"
desc = "Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et!\n\nAtque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["lorem", "ipsum"]
img = "https://placehold.co/600x400"
links = [
    {name = "homepage", url = "https://example.com"},
    {name = "github", url = "https://example.com"},
    {name = "docs", url = "https://example.com"},
]