[[collection]]
type = "entry"
title = "iPhone 19 Pro"
link = "https://example.com"
icon = "/assets/a1.svg"

[[collection]]
type = "entry"
title = "MacBook Pro 14"
link = "https://example.com"
icon = "/assets/a7.svg"

[[collection]]
type = "entry"
title = "iPad Air 15"
link = "https://example.com"
icon = "/assets/a8.svg"

[[collection]]
type = "entry"
title = "Apple TV"
link = "https://example.com"
icon = "/assets/a4.svg"

[[collection]]
type = "entry"
title = "Apple Watch Series 16"
link = "https://example.com"
icon = "/assets/a2.svg"

[[collection]]
type = "entry"
title = "Mac Mini"
link = "https://example.com"
icon = "/assets/a5.svg"

[[collection]]
type = "entry"
title = "iMac"
link = "https://example.com"
icon = "/assets/a6.svg"
