[[collection]]
type = "card_simple"
icon = "/assets/icon-deepseek.svg"
title = "DeepSeek"
content = "AI Researcher"
date = "2025-present"

[[collection]]
type = "card_simple"
icon = "/assets/icon-openai.png"
title = "OpenAI"
content = "Machine Learning Engineer"
date = "2021-2025"

[[collection]]
type = "card_simple"
icon = "/assets/icon-google.webp"
title = "Google"
content = "Backend Engineer"
date = "2018-2022"
