[[collection]]
type = "card"
icon = "/assets/icon-deepseek.svg"
title = "DeepSeek"
subtitle = "AI Researcher"
date = "2025-present"
content = """\
Work on the DeepSeek project, a research project that aims to develop a new generation of AI models that can understand and generate natural language text.

The project is focused on developing models that can generate text that is coherent, informative, and engaging, and that can be used in a wide range of applications, including chatbots, virtual assistants, and content generation tools.
"""

[[collection]]
type = "card"
icon = "/assets/icon-openai.png"
title = "OpenAI"
subtitle = "Machine Learning Engineer"
date = "2021-2025"
content = """\
Alone with the team, I worked on developing new machine learning models and algorithms for a wide range of applications, including natural language processing, computer vision, and reinforcement learning. I also worked on developing new tools and frameworks for training and deploying machine learning models, and on building systems that can scale to handle large amounts of data and compute resources.
"""

[[collection]]
type = "card"
icon = "/assets/icon-google.webp"
title = "Google"
subtitle = "Backend Engineer"
date = "2018-2022"
content = """\
As a backend engineer at Google, I worked on developing and maintaining the backend systems that power Google's search engine, as well as other products and services. I worked on developing new features and improvements for the search engine, as well as on optimizing the performance and scalability of the backend systems.
"""
