[[collection]]
type = "entry"
icon = "/assets/icon-game-6.jpg"
title = "Elden Ring"
subtitle = "200+ hrs"

[[collection]]
type = "entry"
icon = "/assets/icon-game-5.jpg"
title = "Sekiro: Shadows Die Twice"
subtitle = "300+ hrs"

[[collection]]
type = "entry"
icon = "/assets/icon-dead-cells.jpg"
title = "Dead Cells"
subtitle = "80+ hrs"

[[collection]]
type = "entry"
icon = "/assets/icon-game-2.jpg"
title = "Baldur's Gate 3"
subtitle = "100+ hrs"

[[collection]]
type = "entry"
icon = "/assets/icon-game-4.jpg"
title = "It Takes Two"
subtitle = "20+ hrs"

[[collection]]
type = "entry"
icon = "/assets/icon-game-3.jpg"
title = "Monster Hunter: World"
subtitle = "50+ hrs"
