[[collection]]
type = "art_simple"
img = "/assets/movie-6.webp"
link = "https://example.com"
title = "Anatomy of a Fall"

[[collection]]
type = "art_simple"
img = "/assets/movie-9.webp"
link = "https://example.com"
title = "Inception"

[[collection]]
type = "art_simple"
img = "/assets/movie-1.webp"
link = "https://example.com"
title = "一直游到海水变蓝"

[[collection]]
type = "art_simple"
img = "/assets/movie-8.webp"
link = "https://example.com"
title = "Interstellar"

[[collection]]
type = "art_simple"
img = "/assets/movie-3.webp"
link = "https://example.com"
title = "影"

[[collection]]
type = "art_simple"
img = "/assets/movie-7.webp"
link = "https://example.com"
title = "La La Land"

[[collection]]
type = "art_simple"
img = "/assets/movie-10.webp"
link = "https://example.com"
title = "her"

[[collection]]
type = "art_simple"
img = "/assets/movie-4.webp"
link = "https://example.com"
title = "Flipped"

[[collection]]
type = "art_simple"
img = "/assets/movie-12.webp"
link = "https://example.com"
title = "Léon"

[[collection]]
type = "art_simple"
img = "/assets/movie-2.webp"
link = "https://example.com"
title = "千と千尋の神隠し"
