[[collection]]
type = "card_simple"
title = "Tokio"
link = "https://example.com"
content = "An asynchronous runtime for the Rust programming language"
date = "2025"

[[collection]]
type = "card_simple"
title = "Kubernetes"
link = "https://example.com"
content = "Production-Grade Container Scheduling and Management"
date = "2024"

[[collection]]
type = "card_simple"
title = "Next.js"
link = "https://example.com"
content = "React framework for building full-stack web applications"
date = "2022"

[[collection]]
type = "card_simple"
title = "Deno"
link = "https://example.com"
content = "A modern runtime for JavaScript and TypeScript"
date = "2022"

[[collection]]
type = "card_simple"
title = "Grafana"
link = "https://example.com"
content = "The open and composable observability and data visualization platform"
date = "2020"

[[collection]]
type = "card_simple"
title = "Zustand"
link = "https://example.com"
content = "Bear necessities for state management in React"
date = "2021"
