[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=anaconda"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=androidstudio"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=arch"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=astro"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=bash"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=bevy"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=bun"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=cpp"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=dart"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=debian"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=deno"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=docker"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=elysia"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=flutter"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=git"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=github"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=go"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=grafana"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=haskell"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=ai"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=js"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=kubernetes"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=linux"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=neovim"
[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=nix"
[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=pinia"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=react"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=rust"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=svelte"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=typescript"


[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=wasm"

[[collection]]
type = "entry"
link = "https://example.com"
icon = "https://skillicons.dev/icons?i=zig"
