[[collection]]
type = "entry"
title = "Follow"
link = "https://example.com"
icon = "/assets/icon-follow.svg"

[[collection]]
type = "entry"
title = "VSCode"
link = "https://example.com"
icon = "/assets/icon-vsc.png"

[[collection]]
type = "entry"
title = "IntelliJ IDEA"
link = "https://example.com"
icon = "/assets/icon-idea.svg"

[[collection]]
type = "entry"
title = "Zed"
link = "https://example.com"
icon = "/assets/icon-zed.svg"
